SELECT
  DT_INSERT_INBOUND,
  DT_INSERT_OUTBOUND,
  DT_FINISHED,
  STATUS,
  EVENT,
  PAYLOAD,
  INTEGRATION_RESULT
FROM
  TASY.TIE_OUTBOUND
WHERE
  CONSUMER IS NOT NULL
  AND EVENT LIKE '%send.hl7.default.pacs%'
  AND PAYLOAD LIKE '%"entityIdentifierAcessNumberORC":"22198"%'
  AND DT_INSERT_OUTBOUND BETWEEN TO_TIMESTAMP('2025-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                             AND TO_TIMESTAMP('2025-06-25 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
ORDER BY
  DT_INSERT_OUTBOUND DESC;